### ISSUE TITLE
Wrong way to use the config module

### ISSUE THREAD

**Issue by hurngchunlee** [Donders-Institute/data-streamer#31]
https://github.com/Donders-Institute/data-streamer/blob/d797d190fe31a4251b712c8af78d53ea695dde37/streamer-ui/server/routes/mod_authentication.js#L5

@rutgervandeelen The config file should be loaded using the [config module](https://www.npmjs.com/package/config).  This causes the error message I sent you few days ago:

```
streamer4user_ui.1.3z9y783clukw@dccn-pl003.dccn.nl    | internal/modules/cjs/loader.js:638
streamer4user_ui.1.3z9y783clukw@dccn-pl003.dccn.nl    |     throw err;
streamer4user_ui.1.3z9y783clukw@dccn-pl003.dccn.nl    |     ^
streamer4user_ui.1.3z9y783clukw@dccn-pl003.dccn.nl    | 
streamer4user_ui.1.3z9y783clukw@dccn-pl003.dccn.nl    | Error: Cannot find module '/opt/streamer-ui-server/config/streamer-ui-adconfig.json'
streamer4user_ui.1.3z9y783clukw@dccn-pl003.dccn.nl    |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
streamer4user_ui.1.3z9y783clukw@dccn-pl003.dccn.nl    |     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
streamer4user_ui.1.3z9y783clukw@dccn-pl003.dccn.nl    |     at Module.require (internal/modules/cjs/loader.js:692:17)
streamer4user_ui.1.3z9y783clukw@dccn-pl003.dccn.nl    |     at require (internal/modules/cjs/helpers.js:25:18)
streamer4user_ui.1.3z9y783clukw@dccn-pl003.dccn.nl    |     at Object.<anonymous> (/opt/streamer-ui-server/routes/mod_authentication.js:5:18)
streamer4user_ui.1.3z9y783clukw@dccn-pl003.dccn.nl    |     at Module._compile (internal/modules/cjs/loader.js:778:30)
streamer4user_ui.1.3z9y783clukw@dccn-pl003.dccn.nl    |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
streamer4user_ui.1.3z9y783clukw@dccn-pl003.dccn.nl    |     at Module.load (internal/modules/cjs/loader.js:653:32)
streamer4user_ui.1.3z9y783clukw@dccn-pl003.dccn.nl    |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
streamer4user_ui.1.3z9y783clukw@dccn-pl003.dccn.nl    |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

Furthermore, it can only be one `default.json` file that can be further overwritten by `${NODE_ENV}.json` file under the `config` folder.  The value of `${NODE_ENV}` is provided as an environment variable.  In the documentation, it also illustrates a way to use it for different environment (e.g. development, acceptance, production), which we might want to adopt.

**Comment by hurngchunlee** [comment]
Sorry, I double checked it.  The JSON file should be able to be loaded as object simply using the `require` call.  I added few commands to check what is going wrong with the secret files.

**Comment by hurngchunlee** [comment]
Issue resolved after updating the Jenkins and docker-compose.swarm.yml files.  The main issue is that the secret files are not delivered to the container.  I am closing the issue.

@rutgervandeelen sorry for the noise.
